services:
    app:
        build: .
        container_name: node-api
        # Quitamos la línea 'user:' de aquí para que inicie como root
        volumes:
            - ./api:/app/api
            - /app/api/node_modules # Este es el que suele dar error de permisos
        environment:
            - CHOKIDAR_USEPOLLING=true
        expose:
            - "3000"
    gateway:
        image: nginx:stable-alpine
        container_name: nginx-gateway
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
